### ISSUE TITLE
No read to try the work

### ISSUE THREAD

**Issue by alphaonex86** [Shockah/Open-Terraria-Rewrite#3]
No read to try the work, or say the status. Dead project?

**Comment by Shockah** [comment]
Well... No point doing it now, as Terraria is still kicking and getting updates. Guess I'm a bit late to say that...

**Comment by egordorichev** [comment]
If you will continue development, i would like to help you.

**Comment by Shockah** [comment]
@egordorichev I believe there's no point, unless Terraria stops being developed. Also since then a lot has changed in Terraria's code, for the better, which makes me less willing to actually do anything with this project.

The part that could actually be useful for other people would be fully working XNB implementation in Java though. This one would be pretty interesting to see.

**Comment by egordorichev** [comment]
@Shockah, Maybe we can try another gamedev project?
